config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :companies do
      resources :users do
        match :change_password, via: [:get, :patch]
      end

      resources :settings do
        collection do
          patch :update_settings
          patch :add_and_update_property
          patch :add_and_update_asset
          delete :delete_property
          delete :delete_asset
        end
      end
    end
  end

  get "/admin/companies/:c_id/swuser", to: 'admin/companies#swuser', as: :swuser

  post '/login', to: 'login#login'
  get '/login', to: 'login#index', as: :user_login

  get '/login/destroy', to: 'login#destroy', as: :user_logout
  get '/login/forgot', to: 'login#forgot', as: :login_forgot
  post '/login/recover', to: 'login#recover', as: :login_recover
  match '/login/:id/change_password', to: 'login#change_password', as: :login_change_password, via: [:get, :patch]

  get '/login/superadmin', to: 'login#superadmin', as: :login_superadmin
  post '/login/superadmin_auth', to: 'login#superadmin_auth', as: :login_superadmin_auth

  match '/dashboard', to: 'dashboard#index', as: :dashboard, via: [:get]
  get :visits_last_known, to: 'dashboard#visits_last_known'

  resource :profile, only: [:show, :update]
  resource :preference, only: [:show, :update]
  get '/preference/integration_office365', to: 'preferences#integration_office365', as: :preference_integration_office365

  match '/accounts/address_mapping', to:'accounts#address_mapping', as: :account_address_mapping, via: [:get, :post]
  match  '/accounts/import', to:'accounts#import', as: :account_import, via: [:get, :post]
  get  '/accounts/export', to:'accounts#export', as: :account_export
  get  '/accounts/csv_template', to: 'accounts#csv_template', as: :accounts_csv_template
  get  '/accounts/batch', to:'accounts#batch', as: :account_batch
  post '/accounts/batch_notes', to:'accounts#batch_notes', as: :account_batch_notes
  match '/accounts/add_account_properties', to:'accounts#add_account_properties', as: :account_add_account_properties, via: [:get, :post]
  match '/accounts/import_assets', to:'accounts#import_assets', as: :account_import_assets, via: [:get, :post]
  get  '/accounts/properties_csv_template', to: 'accounts#properties_csv_template', as: :accounts_properties_csv_template
  get  '/accounts/assets_csv_template', to: 'accounts#assets_csv_template', as: :accounts_assets_csv_template
  get  '/accounts/notes_csv_template', to: 'accounts#notes_csv_template', as: :accounts_notes_csv_template
  resources :accounts do
    member do
      patch  :update_note
      patch  :update_reminder
      patch  :update_email
      patch  :update_meeting
      patch  :delete_account_attachment
      patch  :update_quote
      delete :delete_reminder
      delete :delete_note
      delete :delete_email
      get    :delete_meeting
      delete :delete_future_meeting
      delete :delete_quote
      get    :search
      get    :get_users_list # get '/accounts/:id/get_users_list', to: 'accounts#get_users_list'
      get    :load_more_conversation_item
      patch  :update_account_contacts
      get    :updated_account
      patch  :add_related_to_account
      get    :contacts_by_name
    end
    collection do
      get :check_account_duplication
      post :add_conversation_attachment
      patch :get_or_delete_conversation_attachment
    end
    resources :contacts, only: [:edit, :create, :update, :destroy]
    resources :addresses, only: [:edit, :create, :update, :destroy]
  end
  resources :company_entities
  resources :users do
    member do
      get :fetch
    end
  end
  resources :notifications, only: [:index, :update]
  get '/n/:id', to: 'notifications#show'
  get '/notifications/account_approve/:account_id/:account_transfer_id', to: 'notifications#account_approve', as: :account_approve
  get '/notifications/account_deny/:account_id/:account_transfer_id', to: 'notifications#account_deny', as: :account_deny
  get '/notifications/conversation_detail', to: 'notifications#conversation_detail', as: :notifications_conversation_detail
  get '/n/:id', to: 'notifications#show'
  post '/users/account_transfers', to: 'users#account_transfers', as: :account_transfers
  post '/users/transfers', to: 'users#transfers', as: :transfers
  match '/users/:id/update_time_zone', to: 'users#update_time_zone', as: :users_update_time_zone, via: [:patch]
  get  '/users/:id/not_update_time_zone', to: 'users#not_update_time_zone', as: :users_not_update_time_zone
  post '/accounts/schedule_meeting', to: 'accounts#schedule_meeting', as: :account_schedule_meeting
  post '/accounts/check_in', to: 'accounts#check_in', as: :account_check_in
  post '/accounts/check_out', to: 'accounts#check_out', as: :account_check_out
  post '/accounts/jump_in', to: 'accounts#jump_in', as: :account_jump_in
  post '/accounts/:id/add_note', to: 'accounts#add_note', as: :account_add_note
  post '/accounts/:id/add_asset', to: 'accounts#add_asset', as: :account_add_asset
  put  '/update_asset', to: 'accounts#update_asset', as: :account_update_asset
  post '/accounts/add_quote', to:'accounts#add_quote', as: :account_add_quote
  post '/accounts/add_reminder', to: 'accounts#add_reminder', as: :account_add_reminder
  post '/accounts/:id/send_email', to: 'accounts#send_email', as: :account_send_email
  post '/accounts/:id/share', to: 'accounts#share', as: :account_share
  post '/accounts/:id/account_attachment',to: "accounts#account_attachment", as: :account_attachment
  get  '/accounts/:id/get_account_list_by_scrolling', to: 'accounts#get_account_list_by_scrolling', as: :account_get_account_list_by_scrolling

  match '/schedule', to: 'schedule#index', as: :schedule, via: [:get]
  get   '/schedule/get_notifiable_users', to: 'schedule#get_notifiable_users', as: :schedule_get_notifiable_users
  patch '/schedule/sort_regular_visits', to: 'schedule#sort_regular_visits', as: :schedule_sort_regular_visits
  get   '/schedule/calendar_event', to: 'schedule#calendar_event', as: :schedule_calendar_event
  get   '/schedule/get_meeting', to: 'schedule#get_meeting', as: :schedule_get_meeting
  get   '/schedule/get_events', to: 'schedule#get_events', as: :schedule_get_events
  get   '/schedule/regular_visits', to: 'schedule#regular_visits', as: :schedule_regular_vists
  get   '/schedule/get_account_list_by_scrolling', to: 'schedule#get_account_list_by_scrolling', as: :schedule_get_account_list_by_scrolling
  match '/media', to: 'media#index', as: :media, via: [:get]
  get   '/schedule/get_account_address', to: 'schedule#get_account_address', as: :schedule_get_account_address
  # get   '/schedule/search_account', to: 'schedule#search_account', as: :schedule_search_account
  post '/media/create_folder', to: 'media#create_folder', as: :create_folder
  post '/media/show', to: 'media#show', as: :show
  get  '/media/show_large_image', to: 'media#show_large_image', as: :show_large_image
  post '/media/save_folder', to: 'media#save_folder', as: :save_folder
  post '/media/destroy', to: 'media#destroy', as: :destroy
  post '/media/destroy_multiple', to: 'media#destroy_multiple', as: :destroy_multiple

  post '/media/upload_file', to: 'media#upload_file', as: :upload_file
  post '/media/email_file', to: 'media#email_file', as: :email_file
  get '/media/download_file/:uid', to: 'media#download_file', as: :download_file_by_uid, via: [:get]
  get '/media/download_file/:url/:name', to: 'media#download_file', as: :download_file, :constraints => { :url => /.*/ }, via: [:get]
  post '/media/rename_media_file', to: 'media#rename_media_file', as: :rename_media_file

  match '/messages', to: 'messages#index', as: :messages, via: [:get]

  match '/company', to: 'company#index', as: :company, via: [:get]
  get '/company/add', to: 'company#add', as: :company_add
  get '/company/edit/:id', to: 'company#edit', as: :company_edit

  # match '/company/add_entity', to: 'company#add_entity', as: :company_add_entity, via: [:get, :post]
  get '/company/edit_entity/:id', to: 'company#edit_entity', as: :company_edit_entity
  get '/company/:id/display_sub_entites', to: 'company#display_sub_entites', as: :company_display_sub_entites
  post '/company/delete/:id', to: 'company#delete', as: :company_delete
  get '/company/default_account_statuses', to: 'company#default_account_statuses', as: :default_account_statuses
  post '/company/account_status', to: 'company#account_status', as: :account_status
  post '/company/:company_id/company_news', to: 'company#company_news', as: :company_news
  delete '/company/:company_id/delete_news', to: 'company#delete_news', as: :delete_news
  # match '/users', to: 'users#index', as: :users, via: [:get]
  # get '/users/new', to: 'users#new', as: :users_new
  # get '/users/edit/:id', to: 'users#edit', as: :users_edit
  # post '/users/save/', to: 'users#save', as: :users_save
  # post '/users/delete/:id', to: 'users#delete', as: :users_delete

  match '/settings', to: 'settings#index', as: :settings, via: [:get]
  get :get_users, to: 'company#get_users'
  patch '/settings/company_level_setting', to: 'settings#company_level_setting', as: :settings_company_level_setting
  root 'login#index'

  get :meeting_report, to: 'reports#meeting_report'
  get :meeting_report_result, to: 'reports#meeting_report_result'

  get :activity_report, to: 'reports#activity_report'
  get :activity_report_result, to: 'reports#activity_report_result'

  get :visits_report, to: 'reports#visits_report'
  get :user_visits, to: 'reports#user_visits'
  get :visits_lastknown, to: 'dashboard#visits_lastknown'
  get :gps_tracking_report, to: 'reports#gps_tracking'
  get '/marker_image/:id', to: 'reports#show_marker'
  resources :task_management

  match '(*any)', to: 'errors#routing', via: [:get, :post]
end

app/models/notification.rb
class Notification < OrchardApiModel
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    current_user_roles = current_user.roles.collect { |r| r.name }
    if current_user_roles.include?("Admin") # || current_user_roles.include?("Entity Admin")
      result = AccountTransfer.pending_approval
      response_code = result.code
      pending_account_transfers = JSON.parse(result.body)
      @pending_account_notifications = pending_account_transfers["account_transfers"].nil? ? {} : pending_account_transfers["account_transfers"]
      @pending_account_notifications.each do |pending_account|
        pending_id = pending_account["id"]
        if pending_id == params[:pending_account_id].to_i
          @pending_account_noti = pending_account
        end
      end
    end
  end

  def account_approve
    result = AccountTransfer.approve(params[:account_id], params[:account_transfer_id])
    response = JSON.parse(result.body)
    response_code = result.code
    if response_code == "200"
      @response_code = true
    else
      @response_code = false
    end
    respond_to do |format|
      format.js
    end
  end


  def account_deny
    result = AccountTransfer.deny(params[:account_id], params[:account_transfer_id])
    response = JSON.parse(result.body)
    response_code = result.code
    if response_code == "200"
      @response_code = true
    else
      @response_code = false
    end
    respond_to do |format|
      format.js
    end
  end

  def update
    begin
      @notification = Notification.find(params[:id])
      @notification.update_attributes(read_at: Time.now)
      notification_info
      @result = true
    rescue
      @result = false
    end
  end

  def show
    session[:previous_url] = nil
    flash.clear
    notification = Notification.find(params[:id]) rescue nil
    flash[:danger] = "Sorry, we're unable to find your notification" unless notification
    render :index
  end

  def conversation_detail
    if params[:notification_read] == 'false'
      @notification = Notification.find(params[:notification_id])
      @notification.update_attributes(read_at: Time.now)
      notification_info
    else
      @notification = Notification.find(params[:notification_id])
    end
    user_ids = Array[]
    user_ids.push(current_user.id)

    @notification_type = params[:notification_type]
    case params[:notification_type]
      when 'reminder'
        search = Hash[]
        search[:id_eq] = params[:conversation_id]
        search[:type_eq] = 'ConversationItems::Reminder'

        @item = ConversationItemSearch.all(params: { user_ids: user_ids, search: search })
      when 'meeting_reminder'
        search = Hash[]
        search[:id_eq] = params[:conversation_id]
        search[:type_eq] = 'ConversationItems::Meeting'

        @item = ConversationItemSearch.all(params: { user_ids: user_ids, search: search })
      when 'meeting'
        search = Hash[]
        search[:id_eq] = params[:conversation_id]
        search[:type_eq] = 'ConversationItems::Meeting'

        @item = ConversationItemSearch.all(params: { user_ids: user_ids, search: search })
      when 'account_status_change'
        begin
          @item = Account.find(params[:conversation_id])
        rescue ActiveResource::ResourceNotFound
          @item = nil
        end
    end
    @notification = { id: params[:item_id], type: params[:notification_type] }
    respond_to do |format|
      if request.format == :html
        format.html {render template: 'notifications/_conversation_details', layout: false}
      else
        format.js
      end
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_account_transfer_pending_approval.html.erb
<tr id="details_tr_<%= pending_account_notifications["account"]["id"] %>" style="display:none">
  <td colspan="3" id="pending_approval">

    <div class="cd-timeline-content shadow_non">
      <span class="cd-date">
        <%=pending_account_notifications["created_at"].to_datetime.in_time_zone(current_user.time_zone).strftime("%a %b %d %Y at %l:%M %p")%>
      </span>
      <span class="pull-right">
        <%=link_to "javascript:void(0)", class: 'btn btn-xs btn-default mr5 close_div' do%>X<%end%>
      </span>
      <h2 class="ci_header">Account Transfer Approval Required For</h2>
      <h2 class="ci_header"><i class="fa fa-briefcase" style="padding-right: 5px;"></i> <%= pending_account_notifications["account"]["name"] %> (<%= pending_account_notifications["account"]["id"] %>) </h2>
      <p>Your attention is required to approval or deny the transfer of the account.<br />
        Please choose Accept or Reject the transfer of the account.</p>
      <p>
      Assigned from Previous to New user:<br />
      <strong class="text-danger" style="padding: 0px 5px 0px 5px;"><%= pending_account_notifications["from_user"]["first_name"]%> <%= pending_account_notifications["from_user"]["last_name"]%></strong>
      <i class="fa fa-hand-o-right"></i>
      <strong class="text-primary" style="padding: 0px 5px 0px 5px;"><%= pending_account_notifications["to_user"]["first_name"]%> <%= pending_account_notifications["to_user"]["last_name"]%></strong>
      </p>
      <div class="col-sm-10 pull-right text-right" id="accept_deny_button_<%= pending_account_notifications["account"]["id"]%>">
        <%=link_to account_deny_path(account_id: pending_account_notifications["account"]["id"], account_transfer_id: pending_account_notifications["id"]), remote: true, class: 'btn btn-xs btn-default mr5 pull-right' do%>Reject<%end%>
        <%=link_to account_approve_path(account_id: pending_account_notifications["account"]["id"], account_transfer_id: pending_account_notifications["id"]),remote: true, class: 'btn btn-xs btn-default mr5 pull-right' do%>Accept<%end%>
      </div>
      <div class="border_top">
        <div class="col-sm-10 pull-right text-right mtop10">
          <%=link_to account_path(pending_account_notifications["account"]["id"]), class: 'btn btn-xs btn-default mr5 pull-right' do%>Go To Account<%end%>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/notifications/_bar_notification_list.html.erb
<style type="text/css">
.notification-icon {
    border-radius: 10%;
    height:30px;
    width:30px;
}
.thumb-img {
    height: 60%;
    position: relative;
    margin-top: 5px;
}
@media only screen and (max-width: 767px) {
.headermenu li:first-child .dropdown-menu{
  margin-right: -175px;
}
}

</style>
<% pending_acc = pending_account_notifications.nil? ? {} : pending_account_notifications %>
<h5 class="title">You Have <%= (unread_items.count + pending_acc.count) %> New Notifications</h5>
<ul class="dropdown-list gen-list">
  <%if pending_account_notifications.present?%>
    <%pending_account_notifications.first(5).each do |pending_account|%>
      <li class="new">
        <%=link_to notifications_path(pending_account_id: pending_account["id"]),remote: true,method: :get do %>
          <span class="thumb notification_calender" style="background: #1d2939;">
            <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-arrow-right.svg" alt="Reminder">
          </span>
          <span class="desc">
            <span class="name">
              <small>
                <p>Account Transfer Approval Required</br>
                <%= pending_account["account"]["name"] %></p>
              </small>
              <span class="badge badge-success">new</span>
            </span>
            <span class="msg"><%=Chronic.parse(pending_account["created_at"]).in_time_zone(current_user.time_zone).strftime("%b %d at %l:%M %p")%></span>
          </span>
        <%end%>
      </li>
    <%end%>
  <%end%>
  <% rest_no = (pending_acc.count < 5) ? (5 - pending_acc.count) : 0 %>
  <% @unread_items.first(rest_no).each do |notification| %>
    <li class="new">
      <%=link_to notifications_conversation_detail_path(notification_id: notification.id, notification_type: notification.type, conversation_id: (notification.type == "meeting_reminder" || notification.type == "meeting")?notification.value.meeting_id : (notification.type == "reminder")?notification.value.reminder_id : notification.value.account_id , item_id: notification.id), remote: true, method: :get do %>
      <% if notification.type == 'reminder' %>
        <span class="thumb notification-icon" style="background: #f0ca45;">
          <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-bell.svg" alt="Reminder">
        </span>
      <% elsif notification.type == 'meeting' || notification.type == 'meeting_reminder'%>
        <span class="thumb notification-icon" style="background:#1cc7c2;">
          <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-calendar.svg" alt="Meeting">
        </span>
      <% elsif notification.type == 'quote' %>
        <span class="thumb notification-icon" style="background:#e91e63;">
          <img  class="thumb-img"  src="/assets/vertical-timeline/img/cd-icon-calculator.svg" alt="Quote">
        </span>
      <% elsif notification.type == 'account_status_change'%>
        <span class="thumb notification-icon" style="background: #333;">
          <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-briefcase.svg" alt="Account Status Change">
        </span>
      <%end%>
      <span class="desc">
        <span class="name">
          <small>
            <%= notification.title == nil ? "Click to see Details" : notification.title %>
          </small>
          <span class="badge badge-success">new</span></span>
        <span class="msg"><%= Chronic.parse(notification.created_at).in_time_zone(current_user.time_zone).strftime("%b %d") %></span>
      </span>
      <%end%>
    </li>
  <%end%>
  <li class="new"><a href="<%= notifications_path %>">Read All Notifications</a></li>
</ul>

app/views/notifications/_conversation_item_notification_modal.html.erb
<div id="ci_notification" class="modal fade conv-item" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" data-backdrop="static" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">&times;</button>
        <h4 class="modal-title">
          <% if @item.is_a?(ActiveResource::Collection) && @item[0].present? %>
            <%if  notification[:type] == 'reminder'%>
              <span style="background: #f0ca45; margin-right: 4px;" class="thumb notification_calender">
                <img alt="Reminder" src="/assets/vertical-timeline/img/cd-icon-bell.svg" class="thumb-img">
              </span><%= @item[0].title == nil ? "Click to see Details" : @item[0].title %>
            <%elsif  notification[:type] == 'meeting_reminder' || notification[:type] == 'meeting'%>
              <span class="thumb notification_calender" style="background:#1cc7c2; margin-right: 4px;">
                <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-calendar.svg" alt="Meeting">
              </span><%= @item[0].title == nil ? "Click to see Details" : @item[0].title %>
            <%elsif  notification[:type] == 'account_status_change'%>
              <span class="thumb notification_calender" style="background: #333; margin-right: 4px;">
                <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-briefcase.svg" alt="Reminder">
              </span><%= @item.name %>
            <%end%>
          <%else%>
            <span style="background: #f0ca45; margin-right: 4px;" class="thumb notification_calender">
            <img alt="Reminder" src="/assets/vertical-timeline/img/cd-icon-bell.svg" class="thumb-img"></span>Sorry, related item has been deleted
          <%end%>
        </h4>
      </div>
      <div class="modal-body">
        Details of the notification:<br>
        <% if @item.is_a?(ActiveResource::Collection) && @item[0].present? && (@notification[:type] == 'meeting' || @notification[:type] == 'meeting_reminder')%>
          <%if @item[0].starts_at.present? && @item[0].ends_at.present? %>
            <span class="cd-date"><%= @item[0].starts_at.to_datetime.in_time_zone(current_user.time_zone).strftime("%a %b %d %Y - %l:%M %p")%> to <%=@item[0].ends_at.to_datetime.in_time_zone(current_user.time_zone).strftime("%l:%M %p")%>&nbsp;&nbsp;</span>
          <% else %>
            <span class="cd-date"><%= @item[0].created_at.to_datetime.in_time_zone(current_user.time_zone).strftime("%a %b %d %Y at %l:%M %p")%></span>
          <% end %>
          <%= get_styled_meetingstatus(@item[0], false) %>
          <h4 class="ci_header" style="color: #333"><%= @item[0].title %></h4>
          <p><span class="subheading">Agenda:<br/></span><%= sanitize @item[0].body %></p>
          <% if (!@item[0].notes.nil?) %>
            <p><span class="subheading">Notes:<br/></span><%= sanitize @item[0].notes %></p>
          <% end %>
          <div class="ci_footer">
            <i class="fa fa-briefcase tooltips mr10" data-toggle="tooltip" data-original-title="Account"></i><%= @item[0].account.try(:name) ? @item[0].account.name : "Account Deleted" %>
          </div>
          <div class="modal-footer">
            <a href="<%= notifications_path %>" class="btn btn-xs btn-default mr5 pull-right">Go To Notification Page</a>
            <%=link_to account_path(@item[0].account_id), class: 'btn btn-xs btn-default mr5 pull-right' do%>Go To Account<%end%>
            <a href="/notifications/<%= notification[:id] %>" data-remote="true" rel="nofollow" data-method="patch" class="btn btn-xs btn-default mr5 pull-right">Marked Read</a>
          </div>
        <% elsif @item.is_a?(ActiveResource::Collection) && @item[0].present? && @notification[:type] == 'reminder' %>
          <%=@item[0].created_at.to_datetime.in_time_zone(current_user.time_zone).strftime("%a %b %d %Y at %l:%M %p")%>
          <br><br>
          <h4 class="ci_header" style="color: #333"><%= @item[0].title %></h4>
          <%= @item[0].title %>
          <div class="ci_footer">
            <i class="fa fa-briefcase tooltips mr10" data-toggle="tooltip" data-original-title="Account"></i><%= @item[0].account.try(:name) ? @item[0].account.name : "Account Deleted" %>
          </div>
          <div class="modal-footer">
            <a href="<%= notifications_path %>" class="btn btn-xs btn-default mr5 pull-right">Go To Notification Page</a>
            <%=link_to account_path(@item[0].account_id), class: 'btn btn-xs btn-default mr5 pull-right' do%>Go To Account<%end%>
            <a href="/notifications/<%= notification[:id] %>" data-remote="true" rel="nofollow" data-method="patch" class="btn btn-xs btn-default mr5 pull-right">Marked Read</a>
          </div>
        <% elsif @item.is_a?(Account) && @notification[:type] == 'account_status_change' %>
          <h4 class="ci_header" style="color: #333"><%= @item.name %></h4>
          <%= get_styled_status(@item, false) %>
          <p><span class="subheading">Assigned To: &nbsp;</span><%= (@item.assigned_to.nil? ? "*Unassigned*" : "#{@item.assigned_to.first_name} #{@item.assigned_to.last_name}") %></p>
          <p>Account status was updated.</p>
          <div class="modal-footer">
            <a href="<%= notifications_path %>" class="btn btn-xs btn-default mr5 pull-right">Go To Notification Page</a>
            <%=link_to account_path(@item.id), class: 'btn btn-xs btn-default mr5 pull-right' do%>Go To Account<%end%>
            <a href="/notifications/<%= notification[:id] %>" data-remote="true" rel="nofollow" data-method="patch" class="btn btn-xs btn-default mr5 pull-right">Marked Read</a>
          </div>
        <%else%>
          <h4 class="ci_header" style="color: #333">Looks like the related item has been deleted.</h4>
          <div class="modal-footer">
            <a href="<%= notifications_path %>" class="btn btn-xs btn-default mr5 pull-right">Go To Notification Page</a>
            <a href="/notifications/<%= notification[:id] %>" data-remote="true" rel="nofollow" data-method="patch" class="btn btn-xs btn-default mr5 pull-right">Marked Read</a>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/notifications/_pageheader.html.erb
      <h2><i class="fa fa-exclamation"></i> Notifications</h2>
      <div class="breadcrumb-wrapper">
        <span class="label"><?php echo date("F j, Y, g:i a"); ?></span>
      </div>

app/views/notifications/_pending_notification_modal.html.erb
<div id="pending_pop_up" class="modal fade pending" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" data-backdrop="static" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">&times;</button>
        <h4 class="modal-title">
          <span class="thumb notification_calender" style="background: #1d2939; margin-right: 4px;">
            <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-arrow-right.svg" alt="Reminder">
          </span>
          Account Transfer Approval Required
        </h4>
      </div>
      <div class="modal-body">
        Details of the notification:<br>
        <%=pending_account_notifications["created_at"].to_datetime.in_time_zone(current_user.time_zone).strftime("%a %b %d %Y at %l:%M %p")%><br><br>
        Account Transfer Approval Required.</br>
        <%= pending_account_notifications["account"]["name"] %>
      </div>
      <div class="modal-footer">
        <%=link_to account_path(pending_account_notifications["account"]["id"]), class: 'btn btn-xs btn-default mr5 pull-right' do%>Go To Account<%end%>
        <a href="<%= notifications_path %>" class="btn btn-xs btn-default mr5 pull-right">Go To Notification Page</a>
      </div>
    </div>
  </div>
</div>

app/views/notifications/account_approve.js.erb
<%if @response_code%>
  var account_id = "<%= params[:account_id]%>"
  $('#accept_deny_button_'+account_id).html('<b>Action Selected:</b> Accept <br> <strong class="text-success">Transfer Completed...</strong>');
  $("#preloader").hide();
<%end%>

app/views/notifications/account_deny.js.erb
<%if @response_code%>
  var account_id = "<%= params[:account_id]%>"
  $('#accept_deny_button_'+account_id).html('<b>Action Selected:</b> Reject <br> <strong class="text-danger">Transfer Cancelled...</strong>');
  $("#preloader").hide();
<%end%>

app/views/notifications/conversation_detail.js.erb
$("#conversation_notification").html("<%=j render 'notifications/conversation_item_notification_modal', notification: @notification%>")
$('#ci_notification').modal('show');
$('.btn-group').removeClass('open');

app/views/notifications/index.js.erb
$("#pending_notification").html("<%=j render 'notifications/pending_notification_modal', pending_account_notifications: @pending_account_noti%>")
$('#pending_pop_up').modal('show');
$('.btn-group').removeClass('open');