config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :companies do
      resources :users do
        match :change_password, via: [:get, :patch]
      end

      resources :settings do
        collection do
          patch :update_settings
          patch :add_and_update_property
          patch :add_and_update_asset
          delete :delete_property
          delete :delete_asset
        end
      end
    end
  end

  get "/admin/companies/:c_id/swuser", to: 'admin/companies#swuser', as: :swuser

  post '/login', to: 'login#login'
  get '/login', to: 'login#index', as: :user_login

  get '/login/destroy', to: 'login#destroy', as: :user_logout
  get '/login/forgot', to: 'login#forgot', as: :login_forgot
  post '/login/recover', to: 'login#recover', as: :login_recover
  match '/login/:id/change_password', to: 'login#change_password', as: :login_change_password, via: [:get, :patch]

  get '/login/superadmin', to: 'login#superadmin', as: :login_superadmin
  post '/login/superadmin_auth', to: 'login#superadmin_auth', as: :login_superadmin_auth

  match '/dashboard', to: 'dashboard#index', as: :dashboard, via: [:get]
  get :visits_last_known, to: 'dashboard#visits_last_known'

  resource :profile, only: [:show, :update]
  resource :preference, only: [:show, :update]
  get '/preference/integration_office365', to: 'preferences#integration_office365', as: :preference_integration_office365

  match '/accounts/address_mapping', to:'accounts#address_mapping', as: :account_address_mapping, via: [:get, :post]
  match  '/accounts/import', to:'accounts#import', as: :account_import, via: [:get, :post]
  get  '/accounts/export', to:'accounts#export', as: :account_export
  get  '/accounts/csv_template', to: 'accounts#csv_template', as: :accounts_csv_template
  get  '/accounts/batch', to:'accounts#batch', as: :account_batch
  post '/accounts/batch_notes', to:'accounts#batch_notes', as: :account_batch_notes
  match '/accounts/add_account_properties', to:'accounts#add_account_properties', as: :account_add_account_properties, via: [:get, :post]
  match '/accounts/import_assets', to:'accounts#import_assets', as: :account_import_assets, via: [:get, :post]
  get  '/accounts/properties_csv_template', to: 'accounts#properties_csv_template', as: :accounts_properties_csv_template
  get  '/accounts/assets_csv_template', to: 'accounts#assets_csv_template', as: :accounts_assets_csv_template
  get  '/accounts/notes_csv_template', to: 'accounts#notes_csv_template', as: :accounts_notes_csv_template
  resources :accounts do
    member do
      patch  :update_note
      patch  :update_reminder
      patch  :update_email
      patch  :update_meeting
      patch  :delete_account_attachment
      patch  :update_quote
      delete :delete_reminder
      delete :delete_note
      delete :delete_email
      get    :delete_meeting
      delete :delete_future_meeting
      delete :delete_quote
      get    :search
      get    :get_users_list # get '/accounts/:id/get_users_list', to: 'accounts#get_users_list'
      get    :load_more_conversation_item
      patch  :update_account_contacts
      get    :updated_account
      patch  :add_related_to_account
      get    :contacts_by_name
    end
    collection do
      get :check_account_duplication
      post :add_conversation_attachment
      patch :get_or_delete_conversation_attachment
    end
    resources :contacts, only: [:edit, :create, :update, :destroy]
    resources :addresses, only: [:edit, :create, :update, :destroy]
  end
  resources :company_entities
  resources :users do
    member do
      get :fetch
    end
  end
  resources :notifications, only: [:index, :update]
  get '/n/:id', to: 'notifications#show'
  get '/notifications/account_approve/:account_id/:account_transfer_id', to: 'notifications#account_approve', as: :account_approve
  get '/notifications/account_deny/:account_id/:account_transfer_id', to: 'notifications#account_deny', as: :account_deny
  get '/notifications/conversation_detail', to: 'notifications#conversation_detail', as: :notifications_conversation_detail
  get '/n/:id', to: 'notifications#show'
  post '/users/account_transfers', to: 'users#account_transfers', as: :account_transfers
  post '/users/transfers', to: 'users#transfers', as: :transfers
  match '/users/:id/update_time_zone', to: 'users#update_time_zone', as: :users_update_time_zone, via: [:patch]
  get  '/users/:id/not_update_time_zone', to: 'users#not_update_time_zone', as: :users_not_update_time_zone
  post '/accounts/schedule_meeting', to: 'accounts#schedule_meeting', as: :account_schedule_meeting
  post '/accounts/check_in', to: 'accounts#check_in', as: :account_check_in
  post '/accounts/check_out', to: 'accounts#check_out', as: :account_check_out
  post '/accounts/jump_in', to: 'accounts#jump_in', as: :account_jump_in
  post '/accounts/:id/add_note', to: 'accounts#add_note', as: :account_add_note
  post '/accounts/:id/add_asset', to: 'accounts#add_asset', as: :account_add_asset
  put  '/update_asset', to: 'accounts#update_asset', as: :account_update_asset
  post '/accounts/add_quote', to:'accounts#add_quote', as: :account_add_quote
  post '/accounts/add_reminder', to: 'accounts#add_reminder', as: :account_add_reminder
  post '/accounts/:id/send_email', to: 'accounts#send_email', as: :account_send_email
  post '/accounts/:id/share', to: 'accounts#share', as: :account_share
  post '/accounts/:id/account_attachment',to: "accounts#account_attachment", as: :account_attachment
  get  '/accounts/:id/get_account_list_by_scrolling', to: 'accounts#get_account_list_by_scrolling', as: :account_get_account_list_by_scrolling

  match '/schedule', to: 'schedule#index', as: :schedule, via: [:get]
  get   '/schedule/get_notifiable_users', to: 'schedule#get_notifiable_users', as: :schedule_get_notifiable_users
  patch '/schedule/sort_regular_visits', to: 'schedule#sort_regular_visits', as: :schedule_sort_regular_visits
  get   '/schedule/calendar_event', to: 'schedule#calendar_event', as: :schedule_calendar_event
  get   '/schedule/get_meeting', to: 'schedule#get_meeting', as: :schedule_get_meeting
  get   '/schedule/get_events', to: 'schedule#get_events', as: :schedule_get_events
  get   '/schedule/regular_visits', to: 'schedule#regular_visits', as: :schedule_regular_vists
  get   '/schedule/get_account_list_by_scrolling', to: 'schedule#get_account_list_by_scrolling', as: :schedule_get_account_list_by_scrolling
  match '/media', to: 'media#index', as: :media, via: [:get]
  get   '/schedule/get_account_address', to: 'schedule#get_account_address', as: :schedule_get_account_address
  # get   '/schedule/search_account', to: 'schedule#search_account', as: :schedule_search_account
  post '/media/create_folder', to: 'media#create_folder', as: :create_folder
  post '/media/show', to: 'media#show', as: :show
  get  '/media/show_large_image', to: 'media#show_large_image', as: :show_large_image
  post '/media/save_folder', to: 'media#save_folder', as: :save_folder
  post '/media/destroy', to: 'media#destroy', as: :destroy
  post '/media/destroy_multiple', to: 'media#destroy_multiple', as: :destroy_multiple

  post '/media/upload_file', to: 'media#upload_file', as: :upload_file
  post '/media/email_file', to: 'media#email_file', as: :email_file
  get '/media/download_file/:uid', to: 'media#download_file', as: :download_file_by_uid, via: [:get]
  get '/media/download_file/:url/:name', to: 'media#download_file', as: :download_file, :constraints => { :url => /.*/ }, via: [:get]
  post '/media/rename_media_file', to: 'media#rename_media_file', as: :rename_media_file

  match '/messages', to: 'messages#index', as: :messages, via: [:get]

  match '/company', to: 'company#index', as: :company, via: [:get]
  get '/company/add', to: 'company#add', as: :company_add
  get '/company/edit/:id', to: 'company#edit', as: :company_edit

  # match '/company/add_entity', to: 'company#add_entity', as: :company_add_entity, via: [:get, :post]
  get '/company/edit_entity/:id', to: 'company#edit_entity', as: :company_edit_entity
  get '/company/:id/display_sub_entites', to: 'company#display_sub_entites', as: :company_display_sub_entites
  post '/company/delete/:id', to: 'company#delete', as: :company_delete
  get '/company/default_account_statuses', to: 'company#default_account_statuses', as: :default_account_statuses
  post '/company/account_status', to: 'company#account_status', as: :account_status
  post '/company/:company_id/company_news', to: 'company#company_news', as: :company_news
  delete '/company/:company_id/delete_news', to: 'company#delete_news', as: :delete_news
  # match '/users', to: 'users#index', as: :users, via: [:get]
  # get '/users/new', to: 'users#new', as: :users_new
  # get '/users/edit/:id', to: 'users#edit', as: :users_edit
  # post '/users/save/', to: 'users#save', as: :users_save
  # post '/users/delete/:id', to: 'users#delete', as: :users_delete

  match '/settings', to: 'settings#index', as: :settings, via: [:get]
  get :get_users, to: 'company#get_users'
  patch '/settings/company_level_setting', to: 'settings#company_level_setting', as: :settings_company_level_setting
  root 'login#index'

  get :meeting_report, to: 'reports#meeting_report'
  get :meeting_report_result, to: 'reports#meeting_report_result'

  get :activity_report, to: 'reports#activity_report'
  get :activity_report_result, to: 'reports#activity_report_result'

  get :visits_report, to: 'reports#visits_report'
  get :user_visits, to: 'reports#user_visits'
  get :visits_lastknown, to: 'dashboard#visits_lastknown'
  get :gps_tracking_report, to: 'reports#gps_tracking'
  get '/marker_image/:id', to: 'reports#show_marker'
  resources :task_management

  match '(*any)', to: 'errors#routing', via: [:get, :post]
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  load_and_authorize_resource class: "SettingsController"
  before_action :application_settings, only: [:index]

  def index
    @company_settings = company_settings_load(true)
    get_account_display_setting
  end

  def company_level_setting
    get_api_values

    params["accounts_by_status"] = "[]" if params["accounts_by_status"].nil?

    @apiFullUrl_authentication = RequestStore.store[:api_url] + "/company/settings/authentication"

    @apiFullUrl_preferences =  RequestStore.store[:api_url] + '/company/settings/preferences'

    authentication_curlRes = `curl -X PUT -H "Authorization: Token token="#{@token}", email="#{@email}", app_key="#{@appKey}"" -H "Content-Type: application/json"  -d '{"settings":{"automatic_logout": "#{params[:automatic_logout]}"}}' '#{@apiFullUrl_authentication}'`

    preferences_curlRes = `curl -X PUT -H "Authorization: Token token="#{@token}", email="#{@email}", app_key="#{@appKey}"" -H "Content-Type: application/json"  -d '{"settings":{"account_per_page": "#{params[:account_per_page]}", "accounts_by_status": #{params[:accounts_by_status]}, "enable_import": "#{params[:enable_import]}", "enable_dst": "#{params[:enable_dst]}", "enable_export": "#{params[:enable_export]}", "enable_expected_sales_attributes": "#{params[:expected_sales_attribute]}", "enable_checkin_checkout": "#{params[:enable_checkin_checkout]}", "enable_timezone_detect": "#{params[:enable_timezone_detect]}", "enable_regular_visits_sort": "#{params[:enable_regular_visits_sort]}", "search_all_accounts": "#{params[:search_all_accounts]}", "needs_approval_for_account_transfer": #{params[:approval_for_account_transfer]}, "visits_preview_range": #{params[:visits_preview_range]}, "visits_expire_range": #{params[:visits_expire_range]}, "gps_tracking_interval": #{params[:gps_tracking_interval]} }}' '#{@apiFullUrl_preferences}'`
    flash[:success] = 'Your setting has been successfully updated!'
    redirect_to settings_path
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
	def perview_timeline_select_options
    return [['1 day',1], ['3 days', 3], ['1 week', 7], ['2 weeks', 14], ['1 month', 31]]
  end

  def automatic_logout_select_options
    return [['1 hour',1], ['2 hours', 2], ['6 hours', 6], ['12 hours', 12], ['1 day', 24], ['3 days', 72], ['5 days', 120]]
  end

  def account_per_page_select_options
    return [['10 accounts',10], ['20 accounts', 20], ['30 accounts', 30], ['40 accounts', 40], ['50 accounts', 50]]
  end

  def account_by_account_status_select_options
    return AccountStatus.all(uid: RequestStore.store[:tenant]).collect{ |a| ["#{a.name}", a.id] }
  end

  def enable_import_export_select_options
    return [['None','none'], ['User', 'user'], ['Entity Admin', 'entity_admin'], ['All', 'all']]
  end

  def enable_disable_options
    return [['Disable', 'disable'],['Enable','enable']]
  end

  def approval_for_account_transfer_options
    return [['By Admins and Entity Admins Only', true],['None', false]]
  end

  def gps_tracking_interval_options
    return [['Off', -1], ['5 secs', 5], ['10 secs', 10], ['30 secs', 30], ['1 min', 60], ['5 mins', 300], ['10 mins', 600], ['15 mins', 900], ['30 mins', 1800], ['45 mins', 2700], ['1 hour', 3600]]
  end

  def general_timeline_select_options
    return [['1 day',1], ['2 days', 2], ['3 days', 3], ['4 days', 4], ['5 days', 5], ['6 days', 6], ['1 week', 7], ['2 weeks', 14], ['3 weeks', 21], ['4 weeks', 28]]
  end

end

app/views/admin/settings/_add_account_property.html.erb
<div class="modal fade add-account-property-modal-form" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" data-backdrop="static" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">&times;</button>
        <h4 class="modal-title">Add Property</h4>
      </div>
      <div class="modal-body">
        <%= form_tag add_property_admin_company_settings_path(company_id: @company), method: :patch do %>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">ID<span class="asterisk">*</span></label>
                </div>
                <div class="col-lg-9">
                  <input type="text" name="property_id" placeholder="" class="form-control" required="required" />
                </div>
              </div>

              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Label<span class="asterisk">*</span></label>
                </div>
                <div class="col-lg-9">
                  <input type="text" name="label" placeholder="" class="form-control" required="required" />
                </div>
              </div>

              <div class="row row-pad-5 form-group">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Required</label>
                </div>
                <div class="col-lg-9">
                  <label class="radio-inline">
                    <input type="radio" name="required" class="form-control" value="false" checked>No
                  </label><br/>
                  <label class="radio-inline">
                    <input type="radio" name="required" class="form-control" value="true">Yes
                  </label>
                </div>
              </div>

              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Format</label>
                </div>
                <div class="col-lg-9">
                  <select class="form-control input-sm mb15" name="format">
                    <option value=''>-select format-</option>
                    <option value="date">Date</option>
                    <option value="numeric">Numeric</option>
                    <option value="enum">Enum</option>
                  </select>
                </div>
              </div>

              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Value</label>
                </div>
                <div class="col-lg-9">
                  <textarea class="form-control" id="" rows="3" placeholder="" name="value"></textarea>
                </div>
              </div>
            </div><!-- panel-body -->

            <div class="panel-footer">
              <%=submit_tag 'Save',  data: {disable_with: "Saving..." }, class: "btn btn-primary"%>
              <button type="reset" class="btn btn-default">Reset</button>
            </div>
          </div><!-- panel -->
        <% end %>
      </div><!-- modal body -->
    </div><!-- modal content -->
  </div><!-- modal dialog -->
</div><!-- modal -->

app/views/admin/settings/_add_and_update_account_property.html.erb
<div class="modal fade add-account-property-modal-form" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" data-backdrop="static" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">&times;</button>
        <h4 class="modal-title property_title">Add Property</h4>
      </div>
      <div class="modal-body">
        <%= form_tag add_and_update_property_admin_company_settings_path(company_id: @company), method: :patch, id: 'add_asset_and_property' do %>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">ID<span class="asterisk">*</span></label>
                </div>
                <div class="col-lg-9">
                  <input type="text" name="property_id" placeholder="" class="form-control property_id" required="required" />
                </div>
              </div>

              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Label<span class="asterisk">*</span></label>
                </div>
                <div class="col-lg-9">
                  <input type="text" name="label" placeholder="" class="form-control property_label" required="required"/>
                </div>
              </div>

              <div class="row row-pad-5 form-group">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Required</label>
                </div>
                <div class="col-lg-9">
                  <div class="radio-inline">
                    <label><input type="radio" name="required" value="false" class="required_false" checked>No</label>
                  </div>
                  <div class="radio-inline">
                    <label><input type="radio" name="required" value="true" class="required_true">Yes</label>
                  </div>
                </div>
              </div>

              <div class="row row-pad-5">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Format</label>
                </div>
                <div class="col-lg-9">
                  <select class="form-control input-sm mb15 property_format" name="format">
                    <option value=''>-select format-</option>
                    <option value="date">Date</option>
                    <option value="numeric">Numeric</option>
                    <option value="enum">Enum</option>
                    <option value="text">Text</option>
                    <option value="select">Select</option>
                  </select>
                </div>
              </div>

              <div class="row row-pad-5 property_value">
                <div class="col-lg-3">
                  <label class="col-sm-3 control-label">Value</label>
                </div>
                <div class="col-lg-9">
                  <textarea class="form-control property_value" rows="3" placeholder="" name="values"></textarea>
                </div>
              </div>
            </div><!-- panel-body -->

            <div class="panel-footer">
              <%=submit_tag 'Save',  data: {disable_with: "Saving..." }, class: "btn btn-primary"%>
              <button type="reset" class="btn btn-default">Reset</button>
            </div>
          </div><!-- panel -->
        <% end %>
      </div><!-- modal body -->
    </div><!-- modal content -->
  </div><!-- modal dialog -->
</div><!-- modal -->

app/views/admin/settings/index.html.erb
<% content_for :pageheader do %>
  <h2><i class="fa fa-cogs"></i>Settings</h2>
<% end %>
<%= form_tag update_settings_admin_company_settings_path(company_id: @company), method: :patch, class: "form-horizontal" do |f| %>
  <div class="profile-header">
    <div class="row row-pad-5">
      <div class="col-md-12 mb20">
        <!-- Nav tabs -->

        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-btns">
              <a href="" class="minimize">−</a>
            </div><!-- panel-btns -->
            <h3 class="panel-title">General Application Settings</h3>
          </div>
          <div class="panel-body">
            <div class="tab-pane" id="authentication">
              <div class="row row-pad-5">
                <div class="form-group">
                  <label class="col-sm-4 control-label">Google Map Autocomplete</label>
                  <div class="col-sm-4">
                    <%=select_tag('googlemap_autocomplete',options_for_select(googlemap_autocomplete_select_options, selected: @googlemap_autocomplete), prompt: '-select-', class: "form-control")%>
                  <p id="googlemap_api_key_warning" style="display: none; color: red; font-size: 9px;"><strong>Warning:</strong> Google Map API Key maybe no longer valid.  Please renew if neccessary.</p>
                  </div>
                </div>
              </div><!-- row pad 5-->
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-btns">
              <a href="" class="minimize">−</a>
            </div><!-- panel-btns -->
            <h3 class="panel-title">Modules</h3>
          </div>
          <div class="panel-body">
            <div class="tab-pane" id="authentication">
              <div class="row row-pad-5">
                <div class="form-group">
                  <label class="col-sm-4 control-label">Assets Management</label>
                  <div class="col-sm-4">
                    <%=select_tag('asset_management',options_for_select(assets_management_select_options, selected: @assets_management), prompt: '-select-', class: "form-control")%>
                  </div>
                </div>
              </div><!-- row pad 5-->
              <div class="row row-pad-5">
                <div class="form-group">
                  <label class="col-sm-4 control-label">Account Attachment</label>
                  <div class="col-sm-4">
                    <%=select_tag('account_attachment',options_for_select(assets_management_select_options, selected: @account_attachment),class: "form-control")%>
                  </div>
                </div>
              </div><!-- row pad 5-->
              <div class="row row-pad-5">
                <div class="form-group">
                  <label class="col-sm-4 control-label">Conversation Item Attachment</label>
                  <div class="col-sm-4">
                    <%=select_tag('conversation_item_attachment',options_for_select(assets_management_select_options, selected: @conversation_item_attachment), class: "form-control")%>
                  </div>
                </div>
              </div><!-- row pad 5-->
              <div class="row row-pad-5">
                <div class="form-group">
                  <label class="col-sm-4 control-label">GPS Tracking</label>
                  <div class="col-sm-4">
                    <%=select_tag('gps_tracking',options_for_select(gps_tracking_select_options, selected: @gps_tracking), class: "form-control")%>
                  </div>
                </div>
              </div><!-- row pad 5-->
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-btns">
              <a href="" class="minimize">−</a>
            </div><!-- panel-btns -->
            <h3 class="panel-title">Integrations</h3>
          </div>
          <div class="panel-body">
            <div class="tab-pane" id="authentication">
              <div class="row row-pad-5">
                <div class="form-group">
                  <label class="col-sm-4 control-label">Office 365</label>
                  <div class="col-sm-4">
                    <%=select_tag('office365_integration',options_for_select(office365_integration_select_options, selected: @office365_integration), prompt: '-select-', class: "form-control")%>
                  </div>
                </div>
              </div><!-- row pad 5-->
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-btns">
              <a href="" class="minimize">−</a>
            </div><!-- panel-btns -->
            <h3 class="panel-title">Account Properties</h3>
          </div>
          <div class="panel-body">
            <div class="tab-pane" id="authentication">
              <div class="row row-pad-5">
                <div class="col-sm-10">
                </div>
                <div class="col-sm-2">
                  <a href="#" data-toggle="modal" class="btn btn-primary btn-block add_property" data-target=".add-account-property-modal-form"><i class="fa fa-plus-circle"></i>&nbsp;&nbsp;&nbsp;Add Property</a>
                </div>
              </div>
              <div class="row row-pad-5">
                <%=render 'account_properties_and_assets_table', property_or_asset: @account_properties, cls: 'edit_property'%>
              </div><!-- row pad 5-->
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-btns">
              <a href="" class="minimize">−</a>
            </div><!-- panel-btns -->
            <h3 class="panel-title">Asset Management Properties</h3>
          </div>
          <div class="panel-body">
            <div class="tab-pane" id="authentication">
              <div class="row row-pad-5">
                <div class="col-sm-10">
                </div>
                <div class="col-sm-2">
                  <a href="#" data-toggle="modal" class="btn btn-primary btn-block add_asset" data-target=".add-account-property-modal-form"><i class="fa fa-plus-circle"></i>&nbsp;&nbsp;&nbsp;Add Asset</a>
                </div>
              </div>
              <div class="row row-pad-5">
                <%=render 'account_properties_and_assets_table', property_or_asset: @assets, cls: 'edit_asset'%>
              </div><!-- row pad 5-->
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-footer">
            <div class="row row-pad-5">
              <div class="col-sm-12 text-center">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-default">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- col- -->
    </div><!-- row -->
  </div><!-- profile-header -->
<%end%>
<%=render 'add_and_update_account_property'%>
<script type="text/javascript">
  $("#accounts_by_status").select2({
    width: '100%',
  });

  $(".add_property, .add_asset").click(function(e){
    var company = '<%=@company.id%>'
    if($(this).hasClass('add_property')){
      $(".property_title").text('Add Property')
      url = "/admin/companies/"+company+"/settings/add_and_update_property"
      $("#add_asset_and_property").attr('action',url)
    }else{
      url = "/admin/companies/"+company+"/settings/add_and_update_asset"
      $("#add_asset_and_property").attr('action',url)
      $(".property_title").text('Add Asset')
    }
    $(".property_value").val(null)
    $(".property_format").val(null)
    $(".property_label").val(null)
    $(".property_id").val(null)
    $(".property_id").prop('readonly', false)
    $(".required_false").attr('checked',true)
    $(".property_value").hide()
  })

  $(".property_format").change(function(){
    if($(this).val() == 'enum' || $(this).val() == 'select'){
      $(".property_value").show(500)
    }else{
      $(".property_value").val(null)
      $(".property_value").hide(500)
    }
  })

  $(".edit_property, .edit_asset").click(function(){
    var company = '<%=@company.id%>'
    if($(this).hasClass('edit_property')){
      $(".property_title").text('Edit Property')
      url = "/admin/companies/"+company+"/settings/add_and_update_property"
      $("#add_asset_and_property").attr('action',url)
    }else{
      url = "/admin/companies/"+company+"/settings/add_and_update_asset"
      $("#add_asset_and_property").attr('action',url)
      $(".property_title").text('Edit Asset')
    }
    $(".property_id").val($(this).data('key'))
    $(".property_id").prop('readonly', true)
    $(".property_label").val($(this).data('label'))
    $(".property_format").val($(this).data('format'))
    if($(this).data('format') == 'enum' || $(this).data('format') == 'select'){
      $(".property_value").show(500)
      $(".property_value").val($(this).data('values'))
    }else{
      $(".property_value").hide(500)
      $(".property_value").val(null)
    }
    if($(this).data('required') == true){
     $(".required_true").attr('checked',true)
    }else{
      $(".required_false").attr('checked',true)
    }
  })
</script>