config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :companies do
      resources :users do
        match :change_password, via: [:get, :patch]
      end

      resources :settings do
        collection do
          patch :update_settings
          patch :add_and_update_property
          patch :add_and_update_asset
          delete :delete_property
          delete :delete_asset
        end
      end
    end
  end

  get "/admin/companies/:c_id/swuser", to: 'admin/companies#swuser', as: :swuser

  post '/login', to: 'login#login'
  get '/login', to: 'login#index', as: :user_login

  get '/login/destroy', to: 'login#destroy', as: :user_logout
  get '/login/forgot', to: 'login#forgot', as: :login_forgot
  post '/login/recover', to: 'login#recover', as: :login_recover
  match '/login/:id/change_password', to: 'login#change_password', as: :login_change_password, via: [:get, :patch]

  get '/login/superadmin', to: 'login#superadmin', as: :login_superadmin
  post '/login/superadmin_auth', to: 'login#superadmin_auth', as: :login_superadmin_auth

  match '/dashboard', to: 'dashboard#index', as: :dashboard, via: [:get]
  get :visits_last_known, to: 'dashboard#visits_last_known'

  resource :profile, only: [:show, :update]
  resource :preference, only: [:show, :update]
  get '/preference/integration_office365', to: 'preferences#integration_office365', as: :preference_integration_office365

  match '/accounts/address_mapping', to:'accounts#address_mapping', as: :account_address_mapping, via: [:get, :post]
  match  '/accounts/import', to:'accounts#import', as: :account_import, via: [:get, :post]
  get  '/accounts/export', to:'accounts#export', as: :account_export
  get  '/accounts/csv_template', to: 'accounts#csv_template', as: :accounts_csv_template
  get  '/accounts/batch', to:'accounts#batch', as: :account_batch
  post '/accounts/batch_notes', to:'accounts#batch_notes', as: :account_batch_notes
  match '/accounts/add_account_properties', to:'accounts#add_account_properties', as: :account_add_account_properties, via: [:get, :post]
  match '/accounts/import_assets', to:'accounts#import_assets', as: :account_import_assets, via: [:get, :post]
  get  '/accounts/properties_csv_template', to: 'accounts#properties_csv_template', as: :accounts_properties_csv_template
  get  '/accounts/assets_csv_template', to: 'accounts#assets_csv_template', as: :accounts_assets_csv_template
  get  '/accounts/notes_csv_template', to: 'accounts#notes_csv_template', as: :accounts_notes_csv_template
  resources :accounts do
    member do
      patch  :update_note
      patch  :update_reminder
      patch  :update_email
      patch  :update_meeting
      patch  :delete_account_attachment
      patch  :update_quote
      delete :delete_reminder
      delete :delete_note
      delete :delete_email
      get    :delete_meeting
      delete :delete_future_meeting
      delete :delete_quote
      get    :search
      get    :get_users_list # get '/accounts/:id/get_users_list', to: 'accounts#get_users_list'
      get    :load_more_conversation_item
      patch  :update_account_contacts
      get    :updated_account
      patch  :add_related_to_account
      get    :contacts_by_name
    end
    collection do
      get :check_account_duplication
      post :add_conversation_attachment
      patch :get_or_delete_conversation_attachment
    end
    resources :contacts, only: [:edit, :create, :update, :destroy]
    resources :addresses, only: [:edit, :create, :update, :destroy]
  end
  resources :company_entities
  resources :users do
    member do
      get :fetch
    end
  end
  resources :notifications, only: [:index, :update]
  get '/n/:id', to: 'notifications#show'
  get '/notifications/account_approve/:account_id/:account_transfer_id', to: 'notifications#account_approve', as: :account_approve
  get '/notifications/account_deny/:account_id/:account_transfer_id', to: 'notifications#account_deny', as: :account_deny
  get '/notifications/conversation_detail', to: 'notifications#conversation_detail', as: :notifications_conversation_detail
  get '/n/:id', to: 'notifications#show'
  post '/users/account_transfers', to: 'users#account_transfers', as: :account_transfers
  post '/users/transfers', to: 'users#transfers', as: :transfers
  match '/users/:id/update_time_zone', to: 'users#update_time_zone', as: :users_update_time_zone, via: [:patch]
  get  '/users/:id/not_update_time_zone', to: 'users#not_update_time_zone', as: :users_not_update_time_zone
  post '/accounts/schedule_meeting', to: 'accounts#schedule_meeting', as: :account_schedule_meeting
  post '/accounts/check_in', to: 'accounts#check_in', as: :account_check_in
  post '/accounts/check_out', to: 'accounts#check_out', as: :account_check_out
  post '/accounts/jump_in', to: 'accounts#jump_in', as: :account_jump_in
  post '/accounts/:id/add_note', to: 'accounts#add_note', as: :account_add_note
  post '/accounts/:id/add_asset', to: 'accounts#add_asset', as: :account_add_asset
  put  '/update_asset', to: 'accounts#update_asset', as: :account_update_asset
  post '/accounts/add_quote', to:'accounts#add_quote', as: :account_add_quote
  post '/accounts/add_reminder', to: 'accounts#add_reminder', as: :account_add_reminder
  post '/accounts/:id/send_email', to: 'accounts#send_email', as: :account_send_email
  post '/accounts/:id/share', to: 'accounts#share', as: :account_share
  post '/accounts/:id/account_attachment',to: "accounts#account_attachment", as: :account_attachment
  get  '/accounts/:id/get_account_list_by_scrolling', to: 'accounts#get_account_list_by_scrolling', as: :account_get_account_list_by_scrolling

  match '/schedule', to: 'schedule#index', as: :schedule, via: [:get]
  get   '/schedule/get_notifiable_users', to: 'schedule#get_notifiable_users', as: :schedule_get_notifiable_users
  patch '/schedule/sort_regular_visits', to: 'schedule#sort_regular_visits', as: :schedule_sort_regular_visits
  get   '/schedule/calendar_event', to: 'schedule#calendar_event', as: :schedule_calendar_event
  get   '/schedule/get_meeting', to: 'schedule#get_meeting', as: :schedule_get_meeting
  get   '/schedule/get_events', to: 'schedule#get_events', as: :schedule_get_events
  get   '/schedule/regular_visits', to: 'schedule#regular_visits', as: :schedule_regular_vists
  get   '/schedule/get_account_list_by_scrolling', to: 'schedule#get_account_list_by_scrolling', as: :schedule_get_account_list_by_scrolling
  match '/media', to: 'media#index', as: :media, via: [:get]
  get   '/schedule/get_account_address', to: 'schedule#get_account_address', as: :schedule_get_account_address
  # get   '/schedule/search_account', to: 'schedule#search_account', as: :schedule_search_account
  post '/media/create_folder', to: 'media#create_folder', as: :create_folder
  post '/media/show', to: 'media#show', as: :show
  get  '/media/show_large_image', to: 'media#show_large_image', as: :show_large_image
  post '/media/save_folder', to: 'media#save_folder', as: :save_folder
  post '/media/destroy', to: 'media#destroy', as: :destroy
  post '/media/destroy_multiple', to: 'media#destroy_multiple', as: :destroy_multiple

  post '/media/upload_file', to: 'media#upload_file', as: :upload_file
  post '/media/email_file', to: 'media#email_file', as: :email_file
  get '/media/download_file/:uid', to: 'media#download_file', as: :download_file_by_uid, via: [:get]
  get '/media/download_file/:url/:name', to: 'media#download_file', as: :download_file, :constraints => { :url => /.*/ }, via: [:get]
  post '/media/rename_media_file', to: 'media#rename_media_file', as: :rename_media_file

  match '/messages', to: 'messages#index', as: :messages, via: [:get]

  match '/company', to: 'company#index', as: :company, via: [:get]
  get '/company/add', to: 'company#add', as: :company_add
  get '/company/edit/:id', to: 'company#edit', as: :company_edit

  # match '/company/add_entity', to: 'company#add_entity', as: :company_add_entity, via: [:get, :post]
  get '/company/edit_entity/:id', to: 'company#edit_entity', as: :company_edit_entity
  get '/company/:id/display_sub_entites', to: 'company#display_sub_entites', as: :company_display_sub_entites
  post '/company/delete/:id', to: 'company#delete', as: :company_delete
  get '/company/default_account_statuses', to: 'company#default_account_statuses', as: :default_account_statuses
  post '/company/account_status', to: 'company#account_status', as: :account_status
  post '/company/:company_id/company_news', to: 'company#company_news', as: :company_news
  delete '/company/:company_id/delete_news', to: 'company#delete_news', as: :delete_news
  # match '/users', to: 'users#index', as: :users, via: [:get]
  # get '/users/new', to: 'users#new', as: :users_new
  # get '/users/edit/:id', to: 'users#edit', as: :users_edit
  # post '/users/save/', to: 'users#save', as: :users_save
  # post '/users/delete/:id', to: 'users#delete', as: :users_delete

  match '/settings', to: 'settings#index', as: :settings, via: [:get]
  get :get_users, to: 'company#get_users'
  patch '/settings/company_level_setting', to: 'settings#company_level_setting', as: :settings_company_level_setting
  root 'login#index'

  get :meeting_report, to: 'reports#meeting_report'
  get :meeting_report_result, to: 'reports#meeting_report_result'

  get :activity_report, to: 'reports#activity_report'
  get :activity_report_result, to: 'reports#activity_report_result'

  get :visits_report, to: 'reports#visits_report'
  get :user_visits, to: 'reports#user_visits'
  get :visits_lastknown, to: 'dashboard#visits_lastknown'
  get :gps_tracking_report, to: 'reports#gps_tracking'
  get '/marker_image/:id', to: 'reports#show_marker'
  resources :task_management

  match '(*any)', to: 'errors#routing', via: [:get, :post]
end

app/helpers/reports_helper.rb
module ReportsHelper


  def meeting_duration(meeting)
  	begin
		  duration = (Time.parse(meeting.ends_at) - Time.parse(meeting.starts_at))
		  time_minutes = ((duration) / 60) % 60
		  time_hours =   duration / (60 * 60)
		  final_duration = format("%2dh %2dmins", time_hours,time_minutes)
  	rescue
      final_duration = nil
  	end
	  return final_duration
  end
end

app/views/reports/_check_in_out.html.erb
<%#@check_in_out = []%>
<%#@#check_in_out << meeting.check_ins if meeting.check_ins.present?%>
<%#@check_in_out << meeting.check_outs if meeting.check_outs.present?%>
<!-- <tr class="meeting_check_in_out_<%=meeting.id%>"> -->
  <%#if @check_in_out.present?%>
<!--       <table>
        <thead>
          <tr>
            <th>Type</th>
            <th>User</th>
            <th>Date/Time</th>
          </tr>
        </thead> -->
        <%#@sort_data = @check_in_out.sort_by {|x| [x.last.user_id, x.last.created_at] }%>
        <%#@sort_data.each do |ci|%>
          <!-- <tbody> -->
        <!--     <tr class="meeting_check_in_out_<%#=meeting.id%>">
              <td></td>
              <td></td>
              <td><b>Type: </b><%#= ci.last.type == 'check_in' ? 'Check In' : 'Check Out'%></td>
              <%#user = User.find(ci.last.user_id)%>
              <td><b>User: </b><%#=user.first_name%> <%= user.last_name%></td>
              <td><b>Date/Time: </b><%#=ci.last.created_at.to_datetime.in_time_zone(current_user.time_zone).strftime("%Y/%m/%d %I:%M:%S %p") rescue nil%></td>
              <td></td>
              <td></td>
              <td></td>
            </tr> -->
          <!-- </tbody> -->
        <%#end%>
      <!-- </table> -->
  <%#else%>
<!--     <td></td>
    <td></td>
    <td>No data available</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td> -->
  <%#end%>
<!-- </tr> -->

app/views/reports/_google_map.html.erb
<div id="map-visits" style="width:100%; height:500px;"></div>

app/views/reports/activity_report.html.erb
<% content_for :pageheader do %>
  <h2><i class="fa fa-briefcase"></i>Account Activity Report</h2>
<% end %>
<div class="contentpanel">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-btns">
        <a href="" class="minimize">−</a>
      </div>
      <h4 class="panel-title">Fill in the details below to get results</h4>
    </div>
    <div class="panel-body">
      <%=form_tag activity_report_result_path, method: :get do%>
        <div class="row mb10">
          <div class="col-sm-6">
            <div class="form-group">
              <label class="control-label">Start Date</label>
              <%if mobile?%>
                <input class="report_from_datepicker" type="date" name="search[date_gteq]" required="required" placeholder="Start Date"/>
              <%else%>
                <input type="text" name="search[date_gteq]" class="form-control report_from_datepicker" placeholder="Start Date" required="required">
              <%end%>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <label class="control-label">End Date</label>
              <%if mobile?%>
                <input  class="report_to_datepicker" type="date" name="search[date_lteq]" required="required" placeholder="End Date"/>
              <%else%>
                <input type="text" class="form-control report_to_datepicker" name="search[date_lteq]" placeholder="End Date" required="required">
              <%end%>
            </div>
          </div>
        </div>
        <%if current_user.roles.last.try(:name) != 'User'%>
          <div class="form-group">
            <label class="control-label">User</label>
            <select class="select" id="select_users" name="users[]" multiple="multiple" required="required" class="form-control" data-placeholder="Filter report by user">
              <% @users.each do |u|%>
                <option value="<%=u.id%>" <%= "selected='selected'" if @users.count == 1 %>><%=u.first_name%> <%=u.last_name%></option>
              <%end%>
              <% if @users.count > 1 %>
                <option value="all">All</option>
              <% end %>
            </select>
          </div>
        <%end%>
        <button type="submit" class="btn btn-primary">Get Report</button>
        <button type="reset" class="btn btn-default">Reset</button>
      <%end%>
    </div>
  </div>
</div>

app/views/reports/activity_report_result.html.erb
<% content_for :pageheader do %>
  <h2><i class="fa fa-briefcase"></i>Activty Report</h2>
<% end %>
<div class="contentpanel">
  <div class="row mb20">
    <div class="col-sm-12">
      See below for the activity report results from <strong><%= params['search']['date_gteq'] %></strong> to <strong><%= params['search']['date_lteq'] %></strong>
    </div>
  </div><!-- row -->
  <div class="row">

    <!-- activity list start -->
    <div class="col-sm-5">
      <div class="panel panel-alt">
        <div class="panel-heading">
          <h3 class="panel-title">Account Acitivty</h3>
        </div>
        <div class="panel-body">
          <small><p>Below is a list of activity by account for the specified date range</p></small>
          <br />
          <div class="feed-activity-list">
            <% if @accounts.count == 0 %>
              <p>No activity to report</p>
            <% else %>
              <% @accounts.each do |a|%>
                <div class="feed-element">
                  <a href="profile.html" class="pull-left">
                    <img alt="image" class="img-circle" src="<%= (a.avatar_url.eql? "/avatars/thumb/missing.png") ? '/assets/images/default_account_avatar.png' : a.avatar_url %>">
                  </a>
                  <div class="media-body ">
                    <small class="pull-right"><%= time_ago_in_words(a.updated_at).gsub('about','') + ' ago' %></small>
                    <strong><%= a.updated_by.try(:first_name) %>&nbsp;<%= a.updated_by.try(:last_name) %></strong>&nbsp;updated the <%= link_to a.name, account_path(a.id) %> account<br>
                    <small class="text-muted"><%= a.updated_at.to_datetime.in_time_zone(current_user.time_zone).strftime("%b %e at %l:%M %p") %></small>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div> <!-- feed activity list -->
        </div><!-- panel-body -->
      </div>
    </div>
    <!-- activity list end -->
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-4">
          <div class="panel panel-stat">
            <div class="panel-heading" style="background-color:#1cc7c2;">
              <div class="stat">
                <div class="row">
                  <div class="col-xs-4">
                    <span class="thumb activity-icon">
                      <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-calendar.svg" alt="General Meetings">
                    </span>
                  </div>
                  <div class="col-xs-8 text-center">
                    <small class="stat-label"><strong>Meetings</strong></small>
                    <h1><%= @totals[:general_meeting] %></h1>
                  </div>
                </div><!-- row -->
              </div><!-- stat -->
            </div><!-- panel-heading -->
          </div>
        </div><!-- tile meeting -->
        <div class="col-sm-4">
          <div class="panel panel-stat">
            <div class="panel-heading" style="background-color:#1cc7c2;">
              <div class="stat">
                <div class="row">
                  <div class="col-xs-4">
                    <span class="thumb activity-icon">
                      <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-calendar.svg" alt="Regular Meetings">
                    </span>
                  </div>
                  <div class="col-xs-8 text-center">
                    <small class="stat-label"><strong>Reg Visits</strong></small>
                    <h1><%= @totals[:regular_meeting] %></h1>
                  </div>
                </div><!-- row -->
              </div><!-- stat -->
            </div><!-- panel-heading -->
          </div>
        </div><!-- tile regular visits -->
        <div class="col-sm-4">
          <div class="panel panel-stat">
            <div class="panel-heading" style="background-color:#e91e63;">
              <div class="stat">
                <div class="row">
                  <div class="col-xs-4">
                    <span class="thumb activity-icon">
                      <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-calculator.svg" alt="Quotes">
                    </span>
                  </div>
                  <div class="col-xs-8 text-center">
                    <small class="stat-label"><strong>Qutoes</strong></small>
                    <h1><%= @sorted_citems[:quote].count %></h1>
                  </div>
                </div><!-- row -->
              </div><!-- stat -->
            </div><!-- panel-heading -->
          </div>
        </div><!-- tile quote -->
      </div>

      <div class="row">
        <div class="col-sm-4">
          <div class="panel panel-stat">
            <div class="panel-heading" style="background-color:#f0ca45;">
              <div class="stat">
                <div class="row">
                  <div class="col-xs-4">
                    <span class="thumb activity-icon">
                      <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-bell.svg" alt="Reminders">
                    </span>
                  </div>
                  <div class="col-xs-8 text-center">
                    <small class="stat-label"><strong>Reminders</strong></small>
                    <h1><%= @sorted_citems[:reminder].count %></h1>
                  </div>
                </div><!-- row -->
              </div><!-- stat -->
            </div><!-- panel-heading -->
          </div>
        </div><!-- tile reminders -->
        <div class="col-sm-4">
          <div class="panel panel-stat">
            <div class="panel-heading" style="background-color:#1c84c6;">
              <div class="stat">
                <div class="row">
                  <div class="col-xs-4">
                    <span class="thumb activity-icon">
                      <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-comments.svg" alt="Notes">
                    </span>
                  </div>
                  <div class="col-xs-8 text-center">
                    <small class="stat-label"><strong>Notes</strong></small>
                    <h1><%=  @sorted_citems[:note].count %></h1>
                  </div>
                </div><!-- row -->
              </div><!-- stat -->
            </div><!-- panel-heading -->
          </div>
        </div><!-- tile notes -->
        <div class="col-sm-4">
          <div class="panel panel-stat">
            <div class="panel-heading" style="background-color:#673AB7;">
              <div class="stat">
                <div class="row">
                  <div class="col-xs-4">
                    <span class="thumb activity-icon">
                      <img class="thumb-img" src="/assets/vertical-timeline/img/cd-icon-envelope-o.svg" alt="Emails">
                    </span>
                  </div>
                  <div class="col-xs-8 text-center">
                    <small class="stat-label"><strong>Emails</strong></small>
                    <h1><%=  @sorted_citems[:email].count %></h1>
                  </div>
                </div><!-- row -->
              </div><!-- stat -->
            </div><!-- panel-heading -->
          </div>
        </div><!-- tile email -->
      </div>

      <div class="row">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#meetings" data-toggle="tab"><strong>Meetings</strong></a></li>
          <li><a href="#regular_meetings" data-toggle="tab"><strong>Reg Visits</strong></a></li>
          <li><a href="#quotes" data-toggle="tab"><strong>Quotes</strong></a></li>
          <li><a href="#reminders" data-toggle="tab"><strong>Reminders</strong></a></li>
          <li><a href="#notes" data-toggle="tab"><strong>Notes</strong></a></li>
          <li><a href="#emails" data-toggle="tab"><strong>Emails</strong></a></li>
        </ul>
        <div class="tab-content mb30">
          <div class="tab-pane active" id="meetings">
            <%= render 'reports/activity_report/meetings_table' %>
          </div>
          <div class="tab-pane" id="regular_meetings">
            <%= render 'reports/activity_report/regular_meetings_table' %>
          </div>
          <div class="tab-pane" id="quotes">
            <%= render 'reports/activity_report/quotes_table' %>
          </div>
          <div class="tab-pane" id="reminders">
            <%= render 'reports/activity_report/reminders_table' %>
          </div>
          <div class="tab-pane" id="notes">
            <%= render 'reports/activity_report/notes_table' %>
          </div>
          <div class="tab-pane" id="emails">
            <%= render 'reports/activity_report/emails_table' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div><!-- contentpanel -->

app/views/reports/check_in_check_out.js.erb
<%#if @success%>
  // if($('.meeting_check_in_out_<%=@meeting.id%>').length > 0){
  //    $('.meeting_check_in_out_<%=@meeting.id%>').remove()
  //   }else{
  //     $("<%= escape_javascript render(:partial => 'check_in_out', locals: { meeting: @meeting }) %>").insertAfter('#meeting_<%=@meeting.id%>');
  //   }
  // $('#preloader').hide();
<%#else%>
  // $('#preloader').hide();
<%#end%>

app/views/reports/meeting_report.html.erb
<% content_for :pageheader do %>
  <h2><i class="fa fa-home"></i> Meetings</h2>
<% end %>
<div class="contentpanel">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-btns">
        <a href="" class="minimize">−</a>
      </div>
      <h4 class="panel-title">Meeting Report Form</h4>
    </div>
    <div class="panel-body">
      <%=form_tag meeting_report_result_path, method: :get do%>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label class="control-label">Start Date</label>
              <%if mobile?%>
                <input class="report_from_datepicker" type="date" name="search[date_gteq]" required="required" placeholder="Start Date"/>
              <%else%>
                <input type="text" name="search[date_gteq]" class="form-control report_from_datepicker" placeholder="Start Date" required="required">
              <%end%>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <label class="control-label">End Date</label>
              <%if mobile?%>
                <input  class="report_to_datepicker" type="date" name="search[date_lteq]" required="required" placeholder="End Date"/>
              <%else%>
                <input type="text" class="form-control report_to_datepicker" name="search[date_lteq]" placeholder="End Date" required="required">
              <%end%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%if current_user.roles.last.try(:name) != 'User'%>
            <label class="control-label">Users</label>
            <select class="select2" id="select_users" name="users[]" multiple="multiple" required="required" class="form-control" data-placeholder="Filter report by user(s)">
              <%= options_for_select(@users.collect{ |u| ["#{u.first_name} #{u.last_name}", u.id] }, selected: current_user.id) %>
              <% if @users.count > 1 %>
                <option value="all">All</option>
              <% end %>
            </select>
          <%end%>
        </div>
        <button type="submit" class="btn btn-primary">Get Report</button>
        <button type="reset" class="btn btn-default">Reset</button>
      <%end%>
    </div>
  </div>
</div>

app/views/reports/sales_report.html.erb
<% content_for :pageheader do %>
  <h2><i class="fa fa-bar-chart-o"></i> Sales</h2>
<% end %>
<div class="contentpanel">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-btns">
        <a href="" class="minimize">−</a>
      </div>
      <h4 class="panel-title">Sales Report Form</h4>
    </div>
    <div class="panel-body">
      <%=form_tag sales_report_result_path, method: :get do%>
        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <label class="control-label">Period</label>
          <%=select_tag('search[period]', options_for_select([['Today', 'today'],['Yesterday', 'yesterday'],['Current Week', 'current_week'],['Current Month', 'current_month'],['Current Year', 'current_year'],['Last Week', 'last_week'],['Last Month', 'last_month'],['Last Year', 'last_year'],['Custom', 'custom']]), {prompt: "-- Select --", :class => 'form-control', required: true})%>
            </div>
          </div>
          <div class="col-sm-9"></div>
        </div>
        <div class="row" id="custom_date_search_report">
          <div class="col-sm-3">
            <div class="form-group">
              <label class="control-label"></label>
              <%if mobile?%>
                <input class="report_from_datepicker" type="date" name="search[date_gteq]" placeholder="Start Date"/>
              <%else%>
                <input type="text" name="search[date_gteq]" class="form-control report_from_datepicker" placeholder="Start Date">
              <%end%>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <label class="control-label"></label>
              <%if mobile?%>
                <input  class="report_to_datepicker" type="date" name="search[date_lteq]" placeholder="End Date"/>
              <%else%>
                <input type="text" class="form-control report_to_datepicker" name="search[date_lteq]" placeholder="End Date">
              <%end%>
            </div>
          </div>
          <div class="col-sm-6"></div>
        </div>
        <div class="row">
          <div class="col-sm-12"><br /></div>
        </div>
        <div class="form-group">
          <%if current_user.roles.last.try(:name) != 'User'%>
            <label class="control-label">Users</label>
            <select class="select2" id="select_users" name="users[]" multiple="multiple" required="required" class="form-control" data-placeholder="Filter report by user(s)">
              <%= options_for_select(@users.collect{ |u| ["#{u.first_name} #{u.last_name}", u.id] }, selected: current_user.id) %>
              <% if @users.count > 1 %>
                <option value="all">All</option>
              <% end %>
            </select>
          <%end%>
        </div>
        <button type="submit" class="btn btn-primary">Get Report</button>
        <button type="reset" class="btn btn-default">Reset</button>
      <%end%>
    </div>
  </div>
</div>


<script>
  $("#custom_date_search_report").hide();
  $(".report_from_datepicker").removeAttr('required');

  $('#search_period').change(function(){
    if ($(this).val() == 'custom') {
      $("#custom_date_search_report").show();
      $(".report_from_datepicker").attr('required', 'true');
    } else {
      $("#custom_date_search_report").hide();
      $(".report_from_datepicker").removeAttr('required');
    }
  });



</script>

app/views/reports/user_visits.js.erb
var locations = <%= raw(@latlng) %>

var map = new google.maps.Map(document.getElementById('map'), {
  zoom: <%= @zoom_level %>,
  center: new google.maps.LatLng(<%= raw(@company_coordinates[:latitude]) %>, <%= raw(@company_coordinates[:longitude]) %>),
  mapTypeId: google.maps.MapTypeId.ROADMAP
});


var marker, i;
var infowindow = new google.maps.InfoWindow();

for (i = 0; i < locations.length; i++) {

  var lat = locations[i][0].toString()
  var lng = locations[i][1].toString()
  var latlang = 'Latitude : ' + lat + ', ' + 'Longitude : ' + lng + '<br/>  Time : ' + locations[i][2]

  marker = new google.maps.Marker({
    position: new google.maps.LatLng(locations[i][0], locations[i][1]),
    icon: {
      path: google.maps.SymbolPath.CIRCLE,
      scale: 10
    },
    draggable: false,
    map: map
  });

  google.maps.event.addListener(marker, 'click', (function(marker, latlang, i) {
    return function() {
      infowindow.setContent(latlang);
      infowindow.open(map, marker);
    }
  })(marker, latlang, i));

}